#ifndef RigAcc_H
#define RigAcc_H

class RIGOL_access:
{
private:
    void add_command(std::string txt);
    char *readline_cmd_generator(const char *text, int state);
    char **readline_completion(const char *text, int start, int);

    unsigned char *recv_data(ViSession &vi, size_t len);
    std::string recv_text(ViSession &vi);
    void flush(ViSession &vi);

public:
    int RIGOL_access(int argc, char **argv);
    ~RIGOL_access();
    bool run_command(ViSession &vi, char *serial, char *command);
    void send_cmd(ViSession &vi, std::string cmd);

       /***
      extracted from DS2000_ProgrammingGuide.pdf:

      pdftotext DS2000_ProgrammingGuide_EN.pdf
      sed -r '/^Syntax/,/^[^:]/ !d; /^:/ ! d; s: .*::; /^:(BUS|CHANnel)<n>/ { h; s/<n>/1/; p; g; s/<n>/2/; };
      		/\[/ { h; s/\[.*\]//; p; g; s/\[//; s/\]//; };' DS2000_ProgrammingGuide_EN.txt | \
      		sed 's:.*:"&",:;' | tr '\n' '\t' | expand -t40 | fold -w160; echo NULL
    ***/
    const char *all_commands_raw = {
        ":AUToscale",                           ":CLEar",                               ":RUN",                                 ":SINGle",
        ":STOP",                                ":TFORce",                              ":TLHAlf",                              ":ACQuire:AVERages",
        ":ACQuire:AVERages?",                   ":ACQuire:MDEPth",                      ":ACQuire:MDEPth?",                     ":ACQuire:SRATe?",
        ":ACQuire:TYPE",                        ":ACQuire:TYPE?",                       ":ACQuire:AALias",                      ":ACQuire:AALias?",
        ":BUS1:MODE",                           ":BUS2:MODE",                           ":BUS1:MODE?",                          ":BUS2:MODE?",
        ":BUS1:DISPlay",                        ":BUS2:DISPlay",                        ":BUS1:DISPlay?",                       ":BUS2:DISPlay?",
        ":BUS1:FORMat",                         ":BUS2:FORMat",                         ":BUS1:FORMat?",                        ":BUS2:FORMat?",
        ":BUS1:EVENt",                          ":BUS2:EVENt",                          ":BUS1:EVENt?",                         ":BUS2:EVENt?",
        ":BUS1:EEXPort",                        ":BUS2:EEXPort",                        ":BUS1:PARallel:CLK",                   ":BUS2:PARallel:CLK",
        ":BUS1:PARallel:CLK?",                  ":BUS2:PARallel:CLK?",                  ":BUS1:PARallel:SLOPe",                 ":BUS2:PARallel:SLOPe",
        ":BUS1:PARallel:SLOPe?",                ":BUS2:PARallel:SLOPe?",                ":BUS1:PARallel:BSET",                  ":BUS2:PARallel:BSET",
        ":BUS1:PARallel:BSET?",                 ":BUS2:PARallel:BSET?",                 ":BUS1:PARallel:THReshold",             ":BUS2:PARallel:THReshold",
        ":BUS1:PARallel:THReshold?",            ":BUS2:PARallel:THReshold?",            ":BUS1:PARallel:OFFSet",                ":BUS2:PARallel:OFFSet",
        ":BUS1:PARallel:OFFSet?",               ":BUS2:PARallel:OFFSet?",               ":BUS1:RS232:TX",                       ":BUS2:RS232:TX",
        ":BUS1:RS232:TX?",                      ":BUS2:RS232:TX?",                      ":BUS1:RS232:RX",                       ":BUS2:RS232:RX",
        ":BUS1:RS232:RX?",                      ":BUS2:RS232:RX?",                      ":BUS1:RS232:POLarity",                 ":BUS2:RS232:POLarity",
        ":BUS1:RS232:POLarity?",                ":BUS2:RS232:POLarity?",                ":BUS1:RS232:ENDian",                   ":BUS2:RS232:ENDian",
        ":BUS1:RS232:ENDian?",                  ":BUS2:RS232:ENDian?",                  ":BUS1:RS232:BAUD",                     ":BUS2:RS232:BAUD",
        ":BUS1:RS232:BAUD?",                    ":BUS2:RS232:BAUD?",                    ":BUS1:RS232:BUSer",                    ":BUS2:RS232:BUSer",
        ":BUS1:RS232:BUSer?",                   ":BUS2:RS232:BUSer?",                   ":BUS1:RS232:DBITs",                    ":BUS2:RS232:DBITs",
        ":BUS1:RS232:DBITs?",                   ":BUS2:RS232:DBITs?",                   ":BUS1:RS232:SBITs",                    ":BUS2:RS232:SBITs",
        ":BUS1:RS232:SBITs?",                   ":BUS2:RS232:SBITs?",                   ":BUS1:RS232:PARity",                   ":BUS2:RS232:PARity",
        ":BUS1:RS232:PARity?",                  ":BUS2:RS232:PARity?",                  ":BUS1:RS232:PACKet",                   ":BUS2:RS232:PACKet",
        ":BUS1:RS232:PACKet?",                  ":BUS2:RS232:PACKet?",                  ":BUS1:RS232:PEND",                     ":BUS2:RS232:PEND",
        ":BUS1:RS232:PEND?",                    ":BUS2:RS232:PEND?",                    ":BUS1:RS232:TTHReshold",               ":BUS2:RS232:TTHReshold",
        ":BUS1:RS232:TTHReshold?",              ":BUS2:RS232:TTHReshold?",              ":BUS1:RS232:RTHReshold",               ":BUS2:RS232:RTHReshold",
        ":BUS1:RS232:RTHReshold?",              ":BUS2:RS232:RTHReshold?",              ":BUS1:RS232:OFFSet",                   ":BUS2:RS232:OFFSet",
        ":BUS1:RS232:OFFSet?",                  ":BUS2:RS232:OFFSet?",                  ":BUS1:IIC:SCLK:SOURce",                ":BUS2:IIC:SCLK:SOURce",
        ":BUS1:IIC:SCLK:SOURce?",               ":BUS2:IIC:SCLK:SOURce?",               ":BUS1:IIC:SCLK:THReshold",             ":BUS2:IIC:SCLK:THReshold",
        ":BUS1:IIC:SCLK:THReshold?",            ":BUS2:IIC:SCLK:THReshold?",            ":BUS1:IIC:SDA:SOURce",                 ":BUS2:IIC:SDA:SOURce",
        ":BUS1:IIC:SDA:SOURce?",                ":BUS2:IIC:SDA:SOURce?",                ":BUS1:IIC:SDA:THReshold",              ":BUS2:IIC:SDA:THReshold",
        ":BUS1:IIC:SDA:THReshold?",             ":BUS2:IIC:SDA:THReshold?",             ":BUS1:IIC:OFFSet",                     ":BUS2:IIC:OFFSet",
        ":BUS1:IIC:OFFSet?",                    ":BUS2:IIC:OFFSet?",                    ":BUS1:SPI:SCLK:SOURce",                ":BUS2:SPI:SCLK:SOURce",
        ":BUS1:SPI:SCLK:SOURce?",               ":BUS2:SPI:SCLK:SOURce?",               ":BUS1:SPI:SCLK:SLOPe",                 ":BUS2:SPI:SCLK:SLOPe",
        ":BUS1:SPI:SCLK:SLOPe?",                ":BUS2:SPI:SCLK:SLOPe?",                ":BUS1:SPI:SCLK:THReshold",             ":BUS2:SPI:SCLK:THReshold",
        ":BUS1:SPI:SCLK:THReshold?",            ":BUS2:SPI:SCLK:THReshold?",            ":BUS1:SPI:SDA:SOURce",                 ":BUS2:SPI:SDA:SOURce",
        ":BUS1:SPI:SDA:SOURce?",                ":BUS2:SPI:SDA:SOURce?",                ":BUS1:SPI:SDA:POLarity",               ":BUS2:SPI:SDA:POLarity",
        ":BUS1:SPI:SDA:POLarity?",              ":BUS2:SPI:SDA:POLarity?",              ":BUS1:SPI:SDA:THReshold",              ":BUS2:SPI:SDA:THReshold",
        ":BUS1:SPI:SDA:THReshold?",             ":BUS2:SPI:SDA:THReshold?",             ":BUS1:SPI:DBITs",                      ":BUS2:SPI:DBITs",
        ":BUS1:SPI:DBITs?",                     ":BUS2:SPI:DBITs?",                     ":BUS1:SPI:ENDian",                     ":BUS2:SPI:ENDian",
        ":BUS1:SPI:ENDian?",                    ":BUS2:SPI:ENDian?",                    ":BUS1:SPI:OFFSet",                     ":BUS2:SPI:OFFSet",
        ":BUS1:SPI:OFFSet?",                    ":BUS2:SPI:OFFSet?",                    ":CALCulate:MODE",                      ":CALCulate:MODE?",
        ":CALCulate:ADD:SA",                    ":CALCulate:ADD:SA?",                   ":CALCulate:ADD:SB",                    ":CALCulate:ADD:SB?",
        ":CALCulate:ADD:INVert",                ":CALCulate:ADD:INVert?",               ":CALCulate:ADD:VSCale",                ":CALCulate:ADD:VSCale?",
        ":CALCulate:ADD:VOFFset",               ":CALCulate:ADD:VOFFset?",              ":CALCulate:SUB:SA",                    ":CALCulate:SUB:SA?",
        ":CALCulate:SUB:SB",                    ":CALCulate:SUB:SB?",                   ":CALCulate:SUB:INVert",                ":CALCulate:SUB:INVert?",
        ":CALCulate:SUB:VSCale",                ":CALCulate:SUB:VSCale?",               ":CALCulate:SUB:VOFFset",               ":CALCulate:SUB:VOFFset?",
        ":CALCulate:MULTiply:SA",               ":CALCulate:MULTiply:SA?",              ":CALCulate:MULTiply:SB",               ":CALCulate:MULTiply:SB?",
        ":CALCulate:MULTiply:INVert",           ":CALCulate:MULTiply:INVert?",          ":CALCulate:MULTiply:VSCale",           ":CALCulate:MULTiply:VSCale?",
        ":CALCulate:MULTiply:VOFFset",          ":CALCulate:MULTiply:VOFFset?",         ":CALCulate:DIVision:SA",               ":CALCulate:DIVision:SA?",
        ":CALCulate:DIVision:SB",               ":CALCulate:DIVision:SB?",              ":CALCulate:DIVision:INVert",           ":CALCulate:DIVision:INVert?",
        ":CALCulate:DIVision:VSCale",           ":CALCulate:DIVision:VSCale?",          ":CALCulate:DIVision:VOFFset",          ":CALCulate:DIVision:VOFFset?",
        ":CALCulate:FFT:SOURce",                ":CALCulate:FFT:SOURce?",               ":CALCulate:FFT:WINDow",                ":CALCulate:FFT:WINDow?",
        ":CALCulate:FFT:SPLit",                 ":CALCulate:FFT:SPLit?",                ":CALCulate:FFT:VSMode",                ":CALCulate:FFT:VSMode?",
        ":CALCulate:FFT:VSCale",                ":CALCulate:FFT:VSCale?",               ":CALCulate:FFT:VOFFset",               ":CALCulate:FFT:VOFFset?",
        ":CALCulate:FFT:HSCale",                ":CALCulate:FFT:HSCale?",               ":CALCulate:FFT:HOFFset",               ":CALCulate:FFT:HOFFset?",
        ":CALCulate:FFT:HSPan",                 ":CALCulate:FFT:HSPan?",                ":CALCulate:FFT:HCENter",               ":CALCulate:FFT:HCENter?",
        ":CALCulate:LOGic:SA",                  ":CALCulate:LOGic:SA?",                 ":CALCulate:LOGic:SB",                  ":CALCulate:LOGic:SB?",
        ":CALCulate:LOGic:INVert",              ":CALCulate:LOGic:INVert?",             ":CALCulate:LOGic:VSCale",              ":CALCulate:LOGic:VSCale?",
        ":CALCulate:LOGic:VOFFset",             ":CALCulate:LOGic:VOFFset?",            ":CALCulate:LOGic:OPERator",            ":CALCulate:LOGic:OPERator?",
        ":CALCulate:LOGic:ATHReshold",          ":CALCulate:LOGic:ATHReshold?",         ":CALCulate:LOGic:BTHReshold",          ":CALCulate:LOGic:BTHReshold?",
        ":CALCulate:ADVanced:EXPRession",       ":CALCulate:ADVanced:EXPRession?",      ":CALCulate:ADVanced:INVert",           ":CALCulate:ADVanced:INVert?",
        ":CALCulate:ADVanced:VARiable1",        ":CALCulate:ADVanced:VARiable1?",       ":CALCulate:ADVanced:VARiable2",        ":CALCulate:ADVanced:VARiable2?",
        ":CALCulate:ADVanced:VSCale",           ":CALCulate:ADVanced:VSCale?",          ":CALCulate:ADVanced:VOFFset",          ":CALCulate:ADVanced:VOFFset?",
        ":CALibrate:DATE?",                     ":CALibrate:STARt",                     ":CALibrate:TIME?",                     ":CALibrate:QUIT",
        ":CHANnel1:BWLimit",                    ":CHANnel2:BWLimit",                    ":CHANnel1:BWLimit?",                   ":CHANnel2:BWLimit?",
        ":CHANnel1:COUPling",                   ":CHANnel2:COUPling",                   ":CHANnel1:COUPling?",                  ":CHANnel2:COUPling?",
        ":CHANnel1:DISPlay",                    ":CHANnel2:DISPlay",                    ":CHANnel1:DISPlay?",                   ":CHANnel2:DISPlay?",
        ":CHANnel1:INVert",                     ":CHANnel2:INVert",                     ":CHANnel1:INVert?",                    ":CHANnel2:INVert?",
        ":CHANnel1:OFFSet",                     ":CHANnel2:OFFSet",                     ":CHANnel1:OFFSet?",                    ":CHANnel2:OFFSet?",
        ":CHANnel1:SCALe",                      ":CHANnel2:SCALe",                      ":CHANnel1:SCALe?",                     ":CHANnel2:SCALe?",
        ":CHANnel1:PROBe",                      ":CHANnel2:PROBe",                      ":CHANnel1:PROBe?",                     ":CHANnel2:PROBe?",
        ":CHANnel1:UNITs",                      ":CHANnel2:UNITs",                      ":CHANnel1:UNITs?",                     ":CHANnel2:UNITs?",
        ":CHANnel1:VERNier",                    ":CHANnel2:VERNier",                    ":CHANnel1:VERNier?",                   ":CHANnel2:VERNier?",
        ":CURSor:MODE",                         ":CURSor:MODE?",                        ":CURSor:MANual:TYPE",                  ":CURSor:MANual:TYPE?",
        ":CURSor:MANual:SOURce",                ":CURSor:MANual:SOURce?",               ":CURSor:MANual:TUNit",                 ":CURSor:MANual:TUNit?",
        ":CURSor:MANual:VUNit",                 ":CURSor:MANual:VUNit?",                ":CURSor:MANual:CAX",                   ":CURSor:MANual:CAX?",
        ":CURSor:MANual:CBX",                   ":CURSor:MANual:CBX?",                  ":CURSor:MANual:CAY",                   ":CURSor:MANual:CAY?",
        ":CURSor:MANual:CBY",                   ":CURSor:MANual:CBY?",                  ":CURSor:MANual:AXValue?",              ":CURSor:MANual:AYValue?",
        ":CURSor:MANual:BXValue?",              ":CURSor:MANual:BYValue?",              ":CURSor:MANual:XDELta?",               ":CURSor:MANual:IXDelta?",
        ":CURSor:MANual:YDELta?",               ":CURSor:TRACk:SOURce1",                ":CURSor:TRACk:SOURce1?",               ":CURSor:TRACk:SOURce2",
        ":CURSor:TRACk:SOURce2?",               ":CURSor:TRACk:CAX",                    ":CURSor:TRACk:CAX?",                   ":CURSor:TRACk:CBX",
        ":CURSor:TRACk:CBX?",                   ":CURSor:TRACk:CAY?",                   ":CURSor:TRACk:CBY?",                   ":CURSor:TRACk:AXValue?",
        ":CURSor:TRACk:AYValue?",               ":CURSor:TRACk:BXValue?",               ":CURSor:TRACk:BYValue?",               ":CURSor:TRACk:XDELta?",
        ":CURSor:TRACk:YDELta?",                ":CURSor:TRACk:IXDelta?",               ":DISPlay:CLEar",                       ":DISPlay:TYPE",
        ":DISPlay:TYPE?",                       ":DISPlay:GRADing:TIME",                ":DISPlay:GRADing:TIME?",               ":DISPlay:WBRightness",
        ":DISPlay:WBRightness?",                ":DISPlay:GRID",                        ":DISPlay:GRID?",                       ":DISPlay:GBRightness",
        ":DISPlay:GBRightness?",                ":DISPlay:MPERsistence",                ":DISPlay:MPERsistence?",               ":DISPlay:DATA?",
        ":FUNCtion:WRMode",                     ":FUNCtion:WRMode?",                    ":FUNCtion:WRECord:FEND",               ":FUNCtion:WRECord:FEND?",
        ":FUNCtion:WRECord:FMAX?",              ":FUNCtion:WRECord:INTerval",           ":FUNCtion:WRECord:INTerval?",          ":FUNCtion:WRECord:OPERate",
        ":FUNCtion:WRECord:OPERate?",           ":FUNCtion:WREPlay:MODE",               ":FUNCtion:WREPlay:MODE?",              ":FUNCtion:WREPlay:INTerval",
        ":FUNCtion:WREPlay:INTerval?",          ":FUNCtion:WREPlay:FSTart",             ":FUNCtion:WREPlay:FSTart?",            ":FUNCtion:WREPlay:FCURrent",
        ":FUNCtion:WREPlay:FCURrent?",          ":FUNCtion:WREPlay:FEND",               ":FUNCtion:WREPlay:FEND?",              ":FUNCtion:WREPlay:FMAX?",
        ":FUNCtion:WREPlay:OPERate",            ":FUNCtion:WREPlay:OPERate?",           ":FUNCtion:WREPlay:TTAG",               ":FUNCtion:WREPlay:TTAG?",
        ":FUNCtion:WREPlay:CTAG?",              ":FUNCtion:WANalyze:MODE",              ":FUNCtion:WANalyze:MODE?",             ":FUNCtion:WANalyze:SOURce",
        ":FUNCtion:WANalyze:SOURce?",           ":FUNCtion:WANalyze:FCURrent",          ":FUNCtion:WANalyze:FCURrent?",         ":FUNCtion:WANalyze:TDISp",
        ":FUNCtion:WANalyze:TDISp?",            ":FUNCtion:WANalyze:SETup:SSTart",      ":FUNCtion:WANalyze:SETup:SSTart?",     ":FUNCtion:WANalyze:SETup:SSENd",
        ":FUNCtion:WANalyze:SETup:SSENd?",      ":FUNCtion:WANalyze:SETup:SFRame",      ":FUNCtion:WANalyze:SETup:SFRame?",     ":FUNCtion:WANalyze:SETup:EFRame",
        ":FUNCtion:WANalyze:SETup:EFRame?",     ":FUNCtion:WANalyze:SETup:THReshold",   ":FUNCtion:WANalyze:SETup:THReshold?",  ":FUNCtion:WANalyze:SETup:XMASk",
        ":FUNCtion:WANalyze:SETup:XMASk?",      ":FUNCtion:WANalyze:SETup:YMASk",       ":FUNCtion:WANalyze:SETup:YMASk?",      ":FUNCtion:WANalyze:STEMplate",
        ":FUNCtion:WANalyze:CMASk",             ":FUNCtion:WANalyze:STARt",             ":FUNCtion:WANalyze:PREVious",          ":FUNCtion:WANalyze:NEXT",
        ":FUNCtion:WANalyze:EFCount?",          ":FUNCtion:WANalyze:ECURrent",          ":FUNCtion:WANalyze:ECURrent?",         ":FUNCtion:WANalyze:ECDiff?",
        ":LAN:DHCP",                            ":LAN:DHCP?",                           ":LAN:AUToip",                          ":LAN:AUToip?",
        ":LAN:GATeway",                         ":LAN:GATeway?",                        ":LAN:DNS",                             ":LAN:DNS?",
        ":LAN:MAC?",                            ":LAN:MANual",                          ":LAN:MANual?",                         ":LAN:INITiate",
        ":LAN:IPADdress",                       ":LAN:IPADdress?",                      ":LAN:SMASk",                           ":LAN:SMASk?",
        ":LAN:STATus?",                         ":LAN:VISA?",                           ":LAN:APPLy",                           ":MASK:ENABle",
        ":MASK:ENABle?",                        ":MASK:SOURce",                         ":MASK:SOURce?",                        ":MASK:OPERate",
        ":MASK:OPERate?",                       ":MASK:MDISplay",                       ":MASK:MDISplay?",                      ":MASK:SOOutput",
        ":MASK:SOOutput?",                      ":MASK:OUTPut",                         ":MASK:OUTPut?",                        ":MASK:X",
        ":MASK:X?",                             ":MASK:Y",                              ":MASK:Y?",                             ":MASK:CREate",
        ":MASK:PASSed?",                        ":MASK:FAILed?",                        ":MASK:TOTal?",                         ":MASK:RESet",
        ":MASK:DATA",                           ":MASK:DATA?",                          ":MEASure:SOURce",                      ":MEASure:SOURce?",
        ":MEASure:COUNter:SOURce",              ":MEASure:COUNter:SOURce?",             ":MEASure:COUNter:VALue?",              ":MEASure:CLEar",
        ":MEASure:RECover",                     ":MEASure:ADISplay",                    ":MEASure:ADISplay?",                   ":MEASure:AMSource",
        ":MEASure:AMSource?",                   ":MEASure:STATistic:DISPlay",           ":MEASure:STATistic:DISPlay?",          ":MEASure:STATistic:MODE",
        ":MEASure:STATistic:MODE?",             ":MEASure:STATistic:RESet",             ":MEASure:SETup:TYPE",                  ":MEASure:SETup:TYPE?",
        ":MEASure:SETup:MAX",                   ":MEASure:SETup:MAX?",                  ":MEASure:SETup:MID",                   ":MEASure:SETup:MID?",
        ":MEASure:SETup:MIN",                   ":MEASure:SETup:MIN?",                  ":MEASure:AREA",                        ":MEASure:AREA?",
        ":MEASure:CREGion:CAX",                 ":MEASure:CREGion:CAX?",                ":MEASure:CREGion:CBX",                 ":MEASure:CREGion:CBX?",
        ":MEASure:HISTory:DISPlay",             ":MEASure:HISTory:DISPlay?",            ":MEASure:HISTory:DMODe",               ":MEASure:HISTory:DMODe?",
        ":MEASure:FDELay?",                     ":MEASure:FDELay:SMAXimum?",            ":MEASure:FDELay:SMINimum?",            ":MEASure:FDELay:SCURrent?",
        ":MEASure:FDELay:SAVerage?",            ":MEASure:FDELay:SDEViation?",          ":MEASure:FPHase?",                     ":MEASure:FPHase:SMAXimum?",
        ":MEASure:FPHase:SMINimum?",            ":MEASure:FPHase:SCURrent?",            ":MEASure:FPHase:SAVerage?",            ":MEASure:FPHase:SDEViation?",
        ":MEASure:FREQuency?",                  ":MEASure:FREQuency:SMAXimum?",         ":MEASure:FREQuency:SMINimum?",         ":MEASure:FREQuency:SCURrent?",
        ":MEASure:FREQuency:SAVerage?",         ":MEASure:FREQuency:SDEViation?",       ":MEASure:FTIMe?",                      ":MEASure:FTIMe:SMAXimum?",
        ":MEASure:FTIMe:SMINimum?",             ":MEASure:FTIMe:SCURrent?",             ":MEASure:FTIMe:SAVerage?",             ":MEASure:FTIMe:SDEViation?",
        ":MEASure:NDUTy?",                      ":MEASure:NDUTy:SMAXimum?",             ":MEASure:NDUTy:SMINimum?",             ":MEASure:NDUTy:SCURrent?",
        ":MEASure:NDUTy:SAVerage?",             ":MEASure:NDUTy:SDEViation?",           ":MEASure:NWIDth?",                     ":MEASure:NWIDth:SMAXimum?",
        ":MEASure:NWIDth:SMAXimum?",            ":MEASure:NWIDth:SCURrent?",            ":MEASure:NWIDth:SAVerage?",            ":MEASure:NWIDth:SDEViation?",
        ":MEASure:OVERshoot?",                  ":MEASure:OVERshoot:SMAXimum?",         ":MEASure:OVERshoot:SMINimum?",         ":MEASure:OVERshoot:SCURrent?",
        ":MEASure:OVERshoot:SAVerage?",         ":MEASure:OVERshoot:SDEViation?",       ":MEASure:PDUTy?",                      ":MEASure:PDUTy:SMAXimum?",
        ":MEASure:PDUTy:SMINimum?",             ":MEASure:PDUTy:SCURrent?",             ":MEASure:PDUTy:SAVerage?",             ":MEASure:PDUTy:SDEViation?",
        ":MEASure:PERiod?",                     ":MEASure:PERiod:SMAXimum?",            ":MEASure:PERiod:SMINimum?",            ":MEASure:PERiod:SCURrent?",
        ":MEASure:PERiod:SAVerage?",            ":MEASure:PERiod:SDEViation?",          ":MEASure:PREShoot?",                   ":MEASure:PREShoot:SMAXimum?",
        ":MEASure:PREShoot:SMINimum?",          ":MEASure:PREShoot:SCURrent?",          ":MEASure:PREShoot:SAVerage?",          ":MEASure:PREShoot:SDEViation?",
        ":MEASure:PWIDth?",                     ":MEASure:PWIDth:SMAXimum?",            ":MEASure:PWIDth:SMINimum?",            ":MEASure:PWIDth:SCURrent?",
        ":MEASure:PWIDth:SAVerage?",            ":MEASure:PWIDth:SDEViation?",          ":MEASure:RTIMe?",                      ":MEASure:RTIMe:SMAXimum?",
        ":MEASure:RTIMe:SMINimum?",             ":MEASure:RTIMe:SCURrent?",             ":MEASure:RTIMe:SAVerage?",             ":MEASure:RTIMe:SDEViation?",
        ":MEASure:RDELay?",                     ":MEASure:RDELay:SMAXimum?",            ":MEASure:RDELay:SMINimum?",            ":MEASure:RDELay:SCURrent?",
        ":MEASure:RDELay:SAVerage?",            ":MEASure:RDELay:SDEViation?",          ":MEASure:RPHase?",                     ":MEASure:RPHase:SMAXimum?",
        ":MEASure:RPHase:SMINimum?",            ":MEASure:RPHase:SCURrent?",            ":MEASure:RPHase:SAVerage?",            ":MEASure:RPHase:SDEViation?",
        ":MEASure:VAMP?",                       ":MEASure:VAMP:SMAXimum?",              ":MEASure:VAMP:SMINimum?",              ":MEASure:VAMP:SCURrent?",
        ":MEASure:VAMP:SAVerage?",              ":MEASure:VAMP:SDEViation?",            ":MEASure:VAVG?",                       ":MEASure:VAVG:SMAXimum?",
        ":MEASure:VAVG:SMINimum?",              ":MEASure:VAVG:SCURrent?",              ":MEASure:VAVG:SAVerage?",              ":MEASure:VAVG:SDEViation?",
        ":MEASure:VBASe?",                      ":MEASure:VBASe:SMAXimum?",             ":MEASure:VBASe:SMINimum?",             ":MEASure:VBASe:SCURrent?",
        ":MEASure:VBASe:SAVerage?",             ":MEASure:VBASe:SDEViation?",           ":MEASure:VMAX?",                       ":MEASure:VMAX:SMAXimum?",
        ":MEASure:VMAX:SMINimum?",              ":MEASure:VMAX:SCURrent?",              ":MEASure:VMAX:SMAXimum?",              ":MEASure:VMAX:SDEViation?",
        ":MEASure:VMIN?",                       ":MEASure:VMIN:SMAXimum?",              ":MEASure:VMIN:SMINimum?",              ":MEASure:VMIN:SCURrent?",
        ":MEASure:VMIN:SAVerage?",              ":MEASure:VMIN:SDEViation?",            ":MEASure:VPP?",                        ":MEASure:VPP:SMAXimum?",
        ":MEASure:VPP:SMINimum?",               ":MEASure:VPP:SCURrent?",               ":MEASure:VPP:SAVerage?",               ":MEASure:VPP:SDEViation?",
        ":MEASure:VRMS?",                       ":MEASure:VRMS:SMAXimum?",              ":MEASure:VRMS:SMINimum?",              ":MEASure:VRMS:SCURrent?",
        ":MEASure:VRMS:SAVerage?",              ":MEASure:VRMS:SDEViation?",            ":MEASure:VTOP?",                       ":MEASure:VTOP:SMAXimum?",
        ":MEASure:VTOP:SMINimum?",              ":MEASure:VTOP:SCURrent?",              ":MEASure:VTOP:SAVerage?",              ":MEASure:VTOP:SDEViation?",
        ":SYSTem:BEEPer",                       ":SYSTem:BEEPer?",                      ":SYSTem:DATE",                         ":SYSTem:DATE?",
        ":SYSTem:TIME",                         ":SYSTem:TIME?",                        ":SYSTem:ERRor?",                       ":SYSTem:ERRor:NEXT?",
        ":SYSTem:EXPand",                       ":SYSTem:EXPand?",                      ":SYSTem:LANGuage",                     ":SYSTem:LANGuage?",
        ":SYSTem:PON",                          ":SYSTem:PON?",                         ":SYSTem:SSAVer:TIME",                  ":SYSTem:SSAVer:TIME?",
        ":SYSTem:SETup",                        ":SYSTem:SETup?",                       ":SYSTem:VERSion?",                     ":SYSTem:AOUTput",
        ":SYSTem:AOUTput?",                     ":SYSTem:RESet",                        ":SYSTem:OPTion:INSTall",               ":SYSTem:OPTion:UNINSTall",
        ":SYSTem:UDEVice",                      ":SYSTem:UDEVice?",                     ":SYSTem:GPIB",                         ":SYSTem:GPIB?",
        ":SYSTem:GAMount?",                     ":SYSTem:RAMount?",                     ":TIMebase:DELay:ENABle",               ":TIMebase:DELay:ENABle?",
        ":TIMebase:DELay:OFFSet",               ":TIMebase:DELay:OFFSet?",              ":TIMebase:DELay:SCALe",                ":TIMebase:DELay:SCALe?",
        ":TIMebase:OFFSet",                     ":TIMebase:MAIN:OFFSet",                ":TIMebase:OFFSet?",                    ":TIMebase:MAIN:OFFSet?",
        ":TIMebase:SCALe",                      ":TIMebase:MAIN:SCALe",                 ":TIMebase:SCALe?",                     ":TIMebase:MAIN:SCALe?",
        ":TIMebase:MODE",                       ":TIMebase:MODE?",                      ":TIMebase:HREF:MODE",                  ":TIMebase:HREF:MODE?",
        ":TIMebase:HREF:POSition",              ":TIMebase:HREF:POSition?",             ":TIMebase:VERNier",                    ":TIMebase:VERNier?",
        ":TRIGger:MODE",                        ":TRIGger:MODE?",                       ":TRIGger:COUPling",                    ":TRIGger:COUPling?",
        ":TRIGger:STATus?",                     ":TRIGger:SWEep",                       ":TRIGger:SWEep?",                      ":TRIGger:HOLDoff",
        ":TRIGger:HOLDoff?",                    ":TRIGger:NREJect",                     ":TRIGger:NREJect?",                    ":TRIGger:EDGe:SOURce",
        ":TRIGger:EDGe:SOURce?",                ":TRIGger:EDGe:SLOPe",                  ":TRIGger:EDGe:SLOPe?",                 ":TRIGger:EDGe:LEVel",
        ":TRIGger:EDGe:LEVel?",                 ":TRIGger:PULSe:SOURce",                ":TRIGger:PULSe:SOURce?",               ":TRIGger:PULSe:WHEN",
        ":TRIGger:PULSe:WHEN?",                 ":TRIGger:PULSe:UWIDth",                ":TRIGger:PULSe:UWIDth?",               ":TRIGger:PULSe:LWIDth",
        ":TRIGger:PULSe:LWIDth?",               ":TRIGger:PULSe:LEVel",                 ":TRIGger:PULSe:LEVel?",                ":TRIGger:RUNT:SOURce",
        ":TRIGger:RUNT:SOURce?",                ":TRIGger:RUNT:POLarity",               ":TRIGger:RUNT:POLarity?",              ":TRIGger:RUNT:WHEN",
        ":TRIGger:RUNT:WHEN?",                  ":TRIGger:RUNT:WLOWer",                 ":TRIGger:RUNT:WLOWer?",                ":TRIGger:RUNT:WUPPer",
        ":TRIGger:RUNT:WUPPer?",                ":TRIGger:RUNT:ALEVel",                 ":TRIGger:RUNT:ALEVel?",                ":TRIGger:RUNT:BLEVel",
        ":TRIGger:RUNT:BLEVel?",                ":TRIGger:WINDows:SOURce",              ":TRIGger:WINDows:SOURce?",             ":TRIGger:WINDows:SLOPe",
        ":TRIGger:RUNT:SLOPe?",                 ":TRIGger:WINDows:POSition",            ":TRIGger:RUNT:POSition?",              ":TRIGger:WINDows:TIMe",
        ":TRIGger:RUNT:TIMe?",                  ":TRIGger:NEDGe:SOURce",                ":TRIGger:NEDGe:SOURce?",               ":TRIGger:NEDGe:SLOPe",
        ":TRIGger:NEDGe:SLOPe?",                ":TRIGger:NEDGe:IDLE",                  ":TRIGger:NEDGe:IDLE?",                 ":TRIGger:NEDGe:EDGE",
        ":TRIGger:NEDGe:EDGE?",                 ":TRIGger:NEDGe:LEVel",                 ":TRIGger:NEDGe:LEVel?",                ":TRIGger:SLOPe:SOURce",
        ":TRIGger:SLOPe:SOURce?",               ":TRIGger:SLOPe:WHEN",                  ":TRIGger:SLOPe:WHEN?",                 ":TRIGger:SLOPe:TUPPer",
        ":TRIGger:SLOPe:TUPPer?",               ":TRIGger:SLOPe:TLOWer",                ":TRIGger:SLOPe:TLOWer?",               ":TRIGger:SLOPe:WINDow",
        ":TRIGger:SLOPe:WINDow?",               ":TRIGger:SLOPe:ALEVel",                ":TRIGger:SLOPe:ALEVel?",               ":TRIGger:SLOPe:BLEVel",
        ":TRIGger:SLOPe:BLEVel?",               ":TRIGger:VIDeo:SOURce",                ":TRIGger:VIDeo:SOURce?",               ":TRIGger:VIDeo:POLarity",
        ":TRIGger:VIDeo:POLarity?",             ":TRIGger:VIDeo:MODE",                  ":TRIGger:VIDeo:MODE?",                 ":TRIGger:VIDeo:LINE",
        ":TRIGger:VIDeo:LINE?",                 ":TRIGger:VIDeo:STANdard",              ":TRIGger:VIDeo:STANdard?",             ":TRIGger:VIDeo:LEVel",
        ":TRIGger:VIDeo:LEVel?",                ":TRIGger:PATTern:PATTern",             ":TRIGger:PATTern:PATTern?",            ":TRIGger:PATTern:LEVel",
        ":TRIGger:PATTern:LEVel?",              ":TRIGger:DELay:SA",                    ":TRIGger:DELay:SA?",                   ":TRIGger:DELay:SLOPA",
        ":TRIGger:DELay:SLOPA?",                ":TRIGger:DELay:SB",                    ":TRIGger:DELay:SB?",                   ":TRIGger:DELay:SLOPB",
        ":TRIGger:DELay:SLOPB?",                ":TRIGger:DELay:TYPe",                  ":TRIGger:DELay:TYPe?",                 ":TRIGger:DELay:TUPPer",
        ":TRIGger:DELay:TUPPer?",               ":TRIGger:DELay:TLOWer",                ":TRIGger:DELay:TLOWer?",               ":TRIGger:TIMeout:SOURce",
        ":TRIGger:TIMeout:SOURce?",             ":TRIGger:TIMeout:SLOPe",               ":TRIGger:TIMeout:SLOPe?",              ":TRIGger:TIMeout:TIMe",
        ":TRIGger:TIMeout:TIMe?",               ":TRIGger:DURATion:SOURce",             ":TRIGger:DURATion:SOURce?",            ":TRIGger:DURATion:TYPe",
        ":TRIGger:DURATion:TYPe?",              ":TRIGger:DURATion:WHEN",               ":TRIGger:DURATion:WHEN?",              ":TRIGger:DURATion:TUPPer",
        ":TRIGger:DURATion:TUPPer?",            ":TRIGger:DURATion:TLOWer",             ":TRIGger:DURATion:TLOWer?",            ":TRIGger:SHOLd:DSrc",
        ":TRIGger:SHOLd:DSrc?",                 ":TRIGger:SHOLd:CSrc",                  ":TRIGger:SHOLd:CSrc?",                 ":TRIGger:SHOLd:SLOPe",
        ":TRIGger:SHOLd:SLOPe?",                ":TRIGger:SHOLd:PATTern",               ":TRIGger:SHOLd:PATTern?",              ":TRIGger:SHOLd:TYPe",
        ":TRIGger:SHOLd:TYPe?",                 ":TRIGger:SHOLd:STIMe",                 ":TRIGger:SHOLd:STIMe?",                ":TRIGger:SHOLd:HTIMe",
        ":TRIGger:SHOLd:HTIMe?",                ":TRIGger:RS232:SOURce",                ":TRIGger:RS232:SOURce?",               ":TRIGger:RS232:WHEN",
        ":TRIGger:RS232:WHEN?",                 ":TRIGger:RS232:PARity",                ":TRIGger:RS232:PARity?",               ":TRIGger:RS232:STOP",
        ":TRIGger:RS232:STOP?",                 ":TRIGger:RS232:DATA",                  ":TRIGger:RS232:DATA?",                 ":TRIGger:RS232:WIDTh",
        ":TRIGger:RS232:WIDTh?",                ":TRIGger:RS232:BAUD",                  ":TRIGger:RS232:BAUD?",                 ":TRIGger:RS232:BUSer",
        ":TRIGger:RS232:BUSer?",                ":TRIGger:RS232:LEVel",                 ":TRIGger:RS232:LEVel?",                ":TRIGger:IIC:SCL",
        ":TRIGger:IIC:SCL?",                    ":TRIGger:IIC:SDA",                     ":TRIGger:IIC:SDA?",                    ":TRIGger:IIC:WHEN",
        ":TRIGger:IIC:WHEN?",                   ":TRIGger:IIC:AWIDth",                  ":TRIGger:IIC:AWIDth?",                 ":TRIGger:IIC:ADDRess",
        ":TRIGger:IIC:ADDRess?",                ":TRIGger:IIC:DIRection",               ":TRIGger:IIC:DIRection?",              ":TRIGger:IIC:DATA",
        ":TRIGger:IIC:DATA?",                   ":TRIGger:IIC:CLEVel",                  ":TRIGger:IIC:CLEVel?",                 ":TRIGger:IIC:DLEVel",
        ":TRIGger:IIC:DLEVel?",                 ":TRIGger:SPI:SCL",                     ":TRIGger:SPI:SCL?",                    ":TRIGger:SPI:SDA",
        ":TRIGger:SPI:SDA?",                    ":TRIGger:SPI:WIDTh",                   ":TRIGger:SPI:WIDTh?",                  ":TRIGger:SPI:DATA",
        ":TRIGger:SPI:DATA?",                   ":TRIGger:SPI:TIMeout",                 ":TRIGger:SPI:TIMeout?",                ":TRIGger:SPI:SLOPe",
        ":TRIGger:SPI:SLOPe?",                  ":TRIGger:SPI:CLEVel",                  ":TRIGger:SPI:CLEVel?",                 ":TRIGger:SPI:DLEVel",
        ":TRIGger:SPI:DLEVel?",                 ":TRIGger:USB:DPLus",                   ":TRIGger:USB:DPLus?",                  ":TRIGger:USB:DMINus",
        ":TRIGger:USB:DMINus?",                 ":TRIGger:USB:SPEed",                   ":TRIGger:USB:SPEed?",                  ":TRIGger:USB:WHEN",
        ":TRIGger:USB:WHEN?",                   ":TRIGger:USB:PLEVel",                  ":TRIGger:USB:PLEVel?",                 ":TRIGger:USB:MLEVel",
        ":TRIGger:USB:MLEVel?",                 ":WAVeform:SOURce",                     ":WAVeform:SOURce?",                    ":WAVeform:MODE",
        ":WAVeform:MODE?",                      ":WAVeform:FORMat",                     ":WAVeform:FORMat?",                    ":WAVeform:POINts",
        ":WAVeform:POINts?",                    ":WAVeform:DATA?",                      ":WAVeform:XINCrement?",                ":WAVeform:XORigin?",
        ":WAVeform:XREFerence?",                ":WAVeform:YINCrement?",                ":WAVeform:YORigin?",                   ":WAVeform:YREFerence?",
        ":WAVeform:STARt",                      ":WAVeform:STARt?",                     ":WAVeform:STOP",                       ":WAVeform:STOP?",
        ":WAVeform:BEGin",                      ":WAVeform:END",                        ":WAVeform:RESet",                      ":WAVeform:PREamble?",
        ":WAVeform:STATus?",                    NULL
    };  
}

#endif
